# -*- coding: utf-8 -*-
"""data_gen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZMaRnL2BIjNZ7nFlRcsGDAji8aR_AGJ

Welcome, in this Jupyter notebook you will find the data generation code used to generate synthetic data for the [digital twin wellness project](https://github.com/AbdulrahmanBHD/digital-twin-wellness)

### 1. We'll start with data synthesis
"""

import numpy as np
import pandas as pd

np.random.seed(42)
n = 365  # one year of data

# Generate features
#steps, movement_mins, calories, diet_qlt, water_l, sleep_mins, sleep_qlt,
#stress_avg, mood_entry_avg, coffee_mg, prod_mins, screen_mins, resting_hr_avg
sleep_hrs = np.clip(np.random.normal(7.2, 1.2, n), 4, 10)
sleep_qlt = np.random.randint(4, 10, n)
steps = np.random.randint(1000, 20000, n)
resting_hr_avg = np.clip(np.random.normal(70, 8, n), 50, 90)
screen_time_hrs = np.clip(np.random.normal(5, 2.5, n), 0, 12)
water_l = np.clip(np.random.normal(2.2, 0.8, n), 0, 4)
stress_avg = np.random.randint(1, 11, n)
caffeine_mg = np.clip(np.random.normal(120, 80, n), 0, 400)
prod_mins = np.random.randint(0, 480, n)
exercise_mins = np.random.randint(0, 180, n)

#Converting hours to minutes (this will also be needed for user input later)
sleep_mins = sleep_hrs * 60
screen_mins = screen_time_hrs * 60

# Normalize for scoring
def normalize(x): return (x - np.min(x)) / (np.max(x) - np.min(x))

wellness = (
    0.3*normalize(sleep_mins) +
    0.2*normalize(sleep_qlt) +
    0.15*normalize(steps) +
   -0.15*normalize(stress_avg) +
   -0.1*normalize(screen_mins) +
    0.1*normalize(exercise_mins) +
    0.05*normalize(water_l) +
    np.random.normal(0, 0.05, n)  # noise
)

# Scale to 0–100
wellness_tmrw = np.clip(100*normalize(wellness), 0, 100)

df = pd.DataFrame({
    "sleep_mins": sleep_mins,
    "sleep_qlt": sleep_qlt,
    "steps": steps,
    "resting_hr_avg": resting_hr_avg,
    "screen_mins": screen_mins,
    "water_l": water_l,
    "stress_1_10": stress_avg,
    "caffeine_mg": caffeine_mg,
    "prod_mins": prod_mins,
    "exercise_mins": exercise_mins,
    "wellness_tmrw": wellness_tmrw
})

df.to_csv("/WDT/data/wellness_synthetic.csv", index=False)
print(df.head())